In [1]:
import os
import sys
sys.path.insert(0, '/tf/develops/Courses/Karakara')

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="1"

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

from tensorflow import keras

In [3]:
import numpy as np
from karakara.layers import BatchNormalization

In [4]:
image = np.arange(64*3*32*32).reshape(64, 3, 32, 32).astype('float32')

In [5]:
image.std()

56755.832

In [8]:
keras_bn_layer = keras.layers.BatchNormalization(axis=1)

krkr_bn_layer = BatchNormalization()
krkr_bn_layer.build((3, 32, 32))

In [9]:
keras_bn_images = keras_bn_layer(image, training=False).numpy()

In [10]:
krkr_bn_images = krkr_bn_layer(image, training=False)

In [12]:
keras_bn_images.mean(axis=(0,2,3))

array([97230.9  , 98254.375, 99277.87 ], dtype=float32)

In [13]:
krkr_bn_images.mean(axis=(0,2,3))

array([97279.5, 98303.5, 99327.5], dtype=float32)

In [14]:
np.std(keras_bn_images, axis=(0,2,3))

array([56721.324, 56721.33 , 56721.33 ], dtype=float32)

In [15]:
np.std(krkr_bn_images, axis=(0,2,3))

array([56749.69, 56749.69, 56749.69], dtype=float32)

In [25]:
import tensorflow as tf

import os
os.environ["CUDA_VISIBLE_DEVICES"]="6"
import warnings
warnings.filterwarnings('ignore')

NUM_EXAMPLES = 1000
training_inputs = np.random.randn(NUM_EXAMPLES)
noise = np.random.randn(NUM_EXAMPLES)
training_outputs = training_inputs * 3 + 2 + noise

def loss(weights, biases):
    error = training_inputs * weights + biases - training_outputs
    return tf.reduce_mean(tf.square(error))

train_steps = 200
learning_rate = 0.01
W = tf.Variable(5.)
B = tf.Variable(10.)

print("Initial loss: {:.3f}".format(loss(W, B)))

for i in range(train_steps):
    dW, dB = 0, 0

    with tf.GradientTape() as tape:
        loss_value = loss(W, B)
        x = loss_value * 2
    dW, dB, dX = tape.gradient(loss_value, [W, B, x])

    W.assign_sub(dW * learning_rate)
    B.assign_sub(dB * learning_rate)
    if i % 20 == 0:
        print(f'dX: {dX}, dW: {dW}, dB: {dB}')

Initial loss: 69.855
dX: None, dW: 5.027900695800781, dB: 16.086477279663086
loss: 67.044
dX: None, dW: 3.035536050796509, dB: 10.681242942810059
loss: 29.715
dX: None, dW: 1.821125864982605, dB: 7.0958356857299805
loss: 13.490
dX: None, dW: 1.0843671560287476, dB: 4.716280460357666
loss: 6.420
dX: None, dW: 0.6398235559463501, dB: 3.136199951171875
loss: 3.331
dX: None, dW: 0.3733154833316803, dB: 2.0864551067352295
loss: 1.978
dX: None, dW: 0.21475979685783386, dB: 1.3887035846710205
loss: 1.384
dX: None, dW: 0.12130283564329147, dB: 0.9246958494186401
loss: 1.123
dX: None, dW: 0.066844642162323, dB: 0.6159852743148804
loss: 1.008
dX: None, dW: 0.03556690365076065, dB: 0.41050341725349426
loss: 0.957
